### ISSUE TITLE
Use <description> in Sublime snippet XML as key in Atom snippet JSON

### ISSUE THREAD

**Issue by jonboiser** [idleberg/atomizr.rb#2]
Example:

```
<snippet>
    <content><![CDATA[
React.createElement('$1', $2, $3)$0
]]>
</content>
    <tabTrigger>rc</tabTrigger>
    <scope>source.js</scope>
    <description>React.createElement()</description>
</snippet>
```

Would be nice if this converted to:

```
  'React.createElement()': # instead of 'rc'
    'prefix': 'rc'
    'body': 'React.createElement(\'$1\', $2, $3)$0'
```

So that users could see the more descriptive 'React.createElement()' in the autocomplete pop-up.

I'm not very experienced with Ruby, but would be happy to attempt a PR for this.

**Comment by idleberg** [comment]
Have a look at the latest master, it now uses `description` if available, otherwise uses `tabTrigger` as fallback.

**Comment by jonboiser** [comment]
Just tried it out. Works great, thanks!
